src/Entity/Annonces.php
<?php

namespace App\Entity;

use App\Repository\AnnoncesRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AnnoncesRepository::class)
 * @Vich\Uploadable
 */
class Annonces
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_on;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="annonces")
     */
    private $author;


    /**
     * @Vich\UploadableField(mapping="annonces_photos", fileNameProperty="photos")
     * @assert\File(
     * maxSize="10M", 
     * mimeTypes = {"image/png" , "image/jpeg"},
     * mimeTypesMessage = "Seules les images jpg et png sont acceptées"
     * )
     */
    private $photosFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photos;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="annonces")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    public function getId(): ?int
    {
        return $this->id;
    }
    public function __toString()
    {
        return $this->title;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedOn(): ?\DateTimeInterface
    {
        return $this->created_on;
    }

    public function setCreatedOn(\DateTimeInterface $created_on): self
    {
        $this->created_on = $created_on;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }
    public function getPhotosFile(): ?File
    {
        return $this->photosFile;
    }
    public function setPhotosFile(?File $photosFile = null): void
    {
        $this->photosFile = $photosFile;

        if ($photosFile !== null){
            $this->updateOn = new \DateTime();
        }
    }

    public function getPhotos(): ?string
    {
        return $this->photos;
    }

    public function setPhotos(?string $photos): self
    {
        $this->photos = $photos;

        return $this;
    }

    public function getCategory(): ?category
    {
        return $this->category;
    }

    public function setCategory(?category $category): self
    {
        $this->category = $category;

        return $this;
    } 
}

src/Controller/LeboncoinController.php
<?php

namespace App\Controller;

use App\Entity\Annonces;
use App\Entity\Category;
use App\Entity\User;
use App\Repository\AnnoncesRepository;
use App\Repository\CategoryRepository;
use Gregwar\CaptchaBundle\Type\CaptchaType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Vich\UploaderBundle\Form\Type\VichImageType;

class LeboncoinController extends AbstractController
{
    /**
     * @Route("/", name="leboncoin_index")
     */
    public function index(Request $request, PaginatorInterface $paginator)
    {
        $annonceRepository = $this->getDoctrine()->getRepository(Annonces::class);
        $annonces = $annonceRepository->findBy([], ['created_on' => 'DESC']);

        $categoryRepository = $this->getDoctrine()->getRepository(Category::class);
        $category = $categoryRepository->findAll();

        $annonces = $paginator->paginate($annonces, $request->query->getInt('page', 1), 6);


        return $this->render('leboncoin/index.html.twig',  [
            'annonces' => $annonces,
            'categories' => $category
        ]);
    }

    /**
     * @Route("/add", name="leboncoin_add")
     */
    public function add(Request $request)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_REMEMBERED');
        $annonces = new Annonces();

        $form = $this->createFormBuilder($annonces)
            ->add('category', EntityType::class, ['class' => Category::class, 'choice_label' => 'name'])
            ->add('title', TextType::class)
            ->add('content', TextareaType::class)
            ->add('price', MoneyType::class, ['divisor' => 100])
            ->add('photosFile', VichImageType::class, ['required' => false])
            ->add('captcha', CaptchaType::class)
            ->add('submit', SubmitType::class, ['label' => 'Valider l\'annonce'])
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $annonces->setCreatedOn(new \DateTime);
            $user = $this->getUser();
            $annonces->setAuthor($user);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($annonces);
            $entityManager->flush();

            $this->addFlash('success', 'Votre annonce a bien été créer !');

            return $this->redirectToRoute('leboncoin_index');
        }
        return $this->render('leboncoin/add.html.twig', ['addForm' => $form->createView()]);
    }
    /**
     * @Route("/annonce/{id}", name="leboncoin_annonce")
     */
    public function annonce($id)
    {
        $annonceRepository = $this->getDoctrine()->getRepository(Annonces::class);
        $annonces = $annonceRepository->find($id);

        return $this->render('leboncoin/annonce.html.twig', ['annonce' => $annonces]);
    }
    /**
     * @Route("/delete/{id}", name="leboncoin_delete")
     */
    public function delete($id)
    {
        $annonceRepository = $this->getDoctrine()->getRepository(Annonces::class);
        $annonce = $annonceRepository->find($id);

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($annonce);
        $entityManager->flush();

        $this->addFlash('success', 'Votre annonce a bie été supprimée !');

        return $this->redirectToRoute('leboncoin_index');
    }
    /**
     * @Route("/edit/{id}", name="leboncoin_edit")
     */
    public function edit($id, Request $request)
    {

        $annonceRepository = $this->getDoctrine()->getRepository(Annonces::class);
        $annonce = $annonceRepository->find($id);
        $annonce->setCreatedOn(new \DateTime);

        $form = $this->createFormBuilder($annonce)
            ->add('category', EntityType::class, ['class' => Category::class, 'choice_label' => 'name'])
            ->add('title', TextType::class)
            ->add('content', TextareaType::class)
            ->add('price', MoneyType::class)
            ->add('photosFile', VichImageType::class, ['required' => false])
            ->add('submit', SubmitType::class, ['label' => 'Editer l\'annonce'])
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->flush();

            $this->addFlash('success', 'Votre annonce a bien été modifiée !');

            return $this->redirectToRoute('leboncoin_annonce', ['id' => $annonce->getId()]);
        }

        return $this->render('leboncoin/edit.html.twig', ['editForm' => $form->createView()]);
    }
    /**
     * @Route("/compte/{id}", name="leboncoin_compte")
     */
    public function editCompte($id, Request $request, UserPasswordEncoderInterface $passwordEncoder)
    {
        $user = $this->getDoctrine()->getRepository(User::class)->find($id);

        $user = $this->getUser();

        $annonceRepository = $this->getDoctrine()->getRepository(Annonces::class);
        $annonces = $annonceRepository->findBy(['author' => $user], ['created_on' => 'DESC']);

        $form = $this->createFormBuilder($user)
            ->add('password', PasswordType::class, ['mapped' => false, 'label' => 'Mot de passe'])
            ->add('submit', SubmitType::class, ['label' => 'Editer votre mot de passe'])
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $user->setPassword($passwordEncoder->encodePassword($user, $form->get('password')->getData()));

            $entityManager = $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', 'Votre mot de passe a bien été changé !');

            return $this->redirectToRoute('leboncoin_compte', ['id' => $user->getId()]);
        }

        return $this->render('leboncoin/compte.html.twig', ['compteForm' => $form->createView(), 'annonces' => $annonces]);
    }

    /**
     * @Route("/category/{name}", name="leboncoin_category")
     */
    public function category($name, CategoryRepository $categoryRepository, AnnoncesRepository $annonceRepository)
    {
        $category = $categoryRepository->findOneBy(['name' => $name]);

        $annonces = $annonceRepository->findBy(['category' => $category]);

        return $this->render('leboncoin/category.html.twig', ['annonces' => $annonces]);
    }
}

templates/leboncoin/add.html.twig
{% extends 'base.html.twig' %}
{% block title %}
	Ecrire une annonce
{% endblock %}
{% block body %}
	{% form_theme addForm 'bootstrap_4_layout.html.twig' %}
    <div class="form_container">
        {{form(addForm)}}
    </div>
	{{ form(addForm) }}{% endblock %}

templates/leboncoin/annonce.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page d'annonce
{% endblock %}

{% block body %}
	<div class="container">
		<div class="row">
			<div class="col-sm">
				<div class="card border-primary text-center">
					<div class="card-header border-primary">
						{{annonce.title}}
					</div>
					<p>
						<div class="card-body">
							<a href="{{ path('leboncoin_annonce', {'id' : annonce.id }) }}" class="btn btn-primary">Plus d'infos</a>
						</p>
					</p>
				</a>
				<p class="card-text">{{annonce.content}}</p>

				Prix :
				<h5 class="card-title">{{annonce.price}}€</h5>

				Vendeur :
				{% if annonce.author %}
					<h5 class="card-title">{{annonce.author.username}}</h5>

					Catégorie :
					<h5 class="card-title">{{annonce.category.name}}</h5>

				{% endif %}
				{% if app.user and app.user == annonce.author %}
					<p>
						<a href="{{ path('leboncoin_delete', {'id' : annonce.id } ) }}">
							<button class="btn btn-danger">Supprimer</button>
						</a>
					</p>
					<p>
						<a href="{{ path('leboncoin_edit', {'id' : annonce.id } ) }}">
							<button class="btn btn-success">Modifier</button>
						</a>
					</p>
				{% endif %}
				<img src="{{asset('uploads/annoncesPictures/') ~ annonce.photos ?? 'default.png'}}" alt="annonces picture">
			</div>
			<div class="card-footer text-muted border-primary">
				{{annonce.createdOn | date('d/m/Y h:i:s')}}
			</div>
		</div>
	</div>
</div></div>{% endblock %}

templates/leboncoin/category.html.twig
{% extends 'base.html.twig' %}
{% block title %}Page d'accueil
{% endblock %}

{% block body %}
		<header>
	{% for annonce in annonces %}
		<div class="container">
		<div class="row">
			<div class="col-sm">
						<div class="card text-center">
							<div class="card-header">
								{{annonce.title}}
							</div>
							<p>
							<div class="card-body">
								<a href="{{ path('leboncoin_annonce', {'id' : annonce.id }) }}" class="btn btn-primary">Plus d'infos</a>
								</p>
							</a>
							<p class="card-text">{{annonce.content}}</p>

							Prix :
							<h5 class="card-title">{{annonce.price}}€</h5>

							Vendeur :
							{% if annonce.author %}
								<h5 class="card-title">{{annonce.author.username}}</h5>

								Catégorie :
								<h5 class="card-title">{{annonce.category.name}}</h5>

							{% endif %}
							{% if app.user and app.user == annonce.author %}
								<p>
									<a href="{{ path('leboncoin_delete', {'id' : annonce.id } ) }}">
										<button class="btn btn-danger">Supprimer</button>
									</a>
								</p>
								<p>
									<a href="{{ path('leboncoin_edit', {'id' : annonce.id } ) }}">
										<button class="btn btn-success">Modifier</button>
									</a>
								</p>
							{% endif %}
							<img src="{{asset('uploads/annoncesPictures/') ~ annonce.photos ?? 'default.png'}}" alt="annonces picture">
						</div>
						<div class="card-footer text-muted">
							{{annonce.createdOn | date('d/m/Y h:i:s')}}
						</div>
					</div>		</div>
	</div>
</div>
	{% endfor %}
{% endblock %}

templates/leboncoin/compte.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Modifiez votre compte
{% endblock %}
{% block body %}
	{% form_theme compteForm 'bootstrap_4_layout.html.twig' %}
	<div class="form_container">
		{{form(compteForm)}}
		</div>
		<header>
			{% for annonce in annonces %}
				<div class="container">
					<div class="row">
						<div class="col-sm">
							<div class="card border-primary text-center">
								<div class="card-header border-primary">
									{{annonce.title}}
								</div>
								<p>
									<div class="card-body">
										<a href="{{ path('leboncoin_annonce', {'id' : annonce.id }) }}" class="btn btn-primary">Plus d'infos</a>
									</p>
								</p>
							</a>
							<p class="card-text">{{annonce.content}}</p>

							Prix :
							<h5 class="card-title">{{annonce.price}}€</h5>

							Vendeur :
							{% if annonce.author %}
								<h5 class="card-title">{{annonce.author.username}}</h5>

								Catégorie :
								<h5 class="card-title">{{annonce.category.name}}</h5>

							{% endif %}
							{% if app.user and app.user == annonce.author %}
								<p>
									<a href="{{ path('leboncoin_delete', {'id' : annonce.id } ) }}">
										<button class="btn btn-danger">Supprimer</button>
									</a>
								</p>
								<p>
									<a href="{{ path('leboncoin_edit', {'id' : annonce.id } ) }}">
										<button class="btn btn-success">Modifier</button>
									</a>
								</p>
							{% endif %}
							<img src="{{asset('uploads/annoncesPictures/') ~ annonce.photos ?? 'default.png'}}" alt="annonces picture">
						</div>
						<div class="card-footer text-muted border-primary">
							{{annonce.createdOn | date('d/m/Y h:i:s')}}
						</div>
					</div>
				</div>
			</div>
		</div>
	{% endfor %}
{% endblock %}

templates/leboncoin/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Modifiez votre annonce
{% endblock %}

{% block body %}
		{% form_theme editForm 'bootstrap_4_layout.html.twig' %}
    <div class="form_container">
        {{form(editForm)}}
    </div>
{% endblock %}

templates/leboncoin/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Page d'accueil
{% endblock %}

{% block body %}
	<div class="categories">
		<div class="dropdown">
			<a class="btn btn-outline-info dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Catégories
			</a>
			<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
				{% for category in categories %}
					<a class="dropdown-item" href="{{ path('leboncoin_category', {'name' : category.name }) }}">{{category.name}}</a>
				{% endfor %}
			</div>
		</div>
	</div>
	{# <a href="{{ path('leboncoin_category', {'name' : category.name }) }}">{{category.name}}</a> #}
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm">
				{% for annonce in annonces %}
					<div class="annonce card border-primary text-center bg-light mb-3">
						<div class="card-header border-primary">
							{{annonce.title}}
						</div>
						<p>
							<div class="card-body">
								<a href="{{ path('leboncoin_annonce', {'id' : annonce.id }) }}" class="btn btn-primary">Plus d'infos</a>
							</p>
						</p>
					</a>

					Prix :
					<h5 class="card-title">{{annonce.price}}€</h5>

					Vendeur :
					{% if annonce.author %}
						<h5 class="card-title">{{annonce.author.username}}</h5>

						Catégorie :
						<h5 class="card-title">{{annonce.category.name}}</h5>

					{% endif %}
					{% if app.user and app.user == annonce.author %}
						<p>
							<a href="{{ path('leboncoin_delete', {'id' : annonce.id } ) }}">
								<button class="btn btn-danger">Supprimer</button>
							</a>
						</p>
						<p>
							<a href="{{ path('leboncoin_edit', {'id' : annonce.id } ) }}">
								<button class="btn btn-success">Modifier</button>
							</a>
						</p>
					{% endif %}
					<img src="{{asset('uploads/annoncesPictures/') ~ annonce.photos ?? 'default.png'}}" alt="annonces picture">
				</div>
				<div class="card-footer text-muted border-primary">
					{{annonce.createdOn | date('d/m/Y h:i:s')}}
				</div>
			</div>
		{% endfor %}
	</div>
</div></div><div class="pagination pagination-lg">
<div class="page-item disabled">
	{{ knp_pagination_render(annonces) }}</div></div>{% endblock %}

templates/leboncoin/moncompte.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Modifiez votre compte
{% endblock %}

{% block body %}
	<header>
		<h1>
			Modifiez votre mot de passe
		</h1>
	</header>
	{{ form(editForm) }}{% endblock %}